In [4]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 


In [5]:
data=pd.read_csv('iris_data.csv') 
print(data.head()) 


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


In [11]:
x=data.drop(columns=['species']) 
y=data['species'] 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20) 



In [14]:
#print(x_train) 
scaler=StandardScaler() 
scaler.fit(x_train) 
#print(x_train) 
x_train=scaler.transform(x_train) 
x_test=scaler.transform(x_test) 
print(x_train) 



[[-0.30921699 -0.5729167   0.6131478   1.01193831]
 [ 1.54608497  1.32363514  1.28714233  1.65580149]
 [-0.88899886  1.08656616 -1.35266958 -1.17719652]
 [ 1.19821585  0.37535922  1.06247749  1.39825622]
 [-0.54112974  0.84949718 -1.18417095 -1.30596916]
 [-1.70069346 -0.33584772 -1.35266958 -1.30596916]
 [-1.46878072  0.13829024 -1.29650337 -1.30596916]
 [ 0.50247761 -0.80998568  0.6131478   0.75439303]
 [-1.00495523  1.32363514 -1.35266958 -1.30596916]
 [ 1.54608497  0.37535922  1.23097612  0.75439303]
 [ 0.27056487 -0.33584772  0.50081538  0.23930248]
 [ 0.1546085  -1.99533059  0.1076519  -0.27578806]
 [ 1.19821585  0.13829024  0.89397886  1.14071094]
 [-1.1209116   0.13829024 -1.29650337 -1.4347418 ]
 [-1.46878072  1.32363514 -1.57733442 -1.30596916]
 [-0.30921699 -0.80998568  0.21998433  0.11052985]
 [ 0.9663031  -0.09877874  0.66931401  0.62562039]
 [-0.54112974  2.03484209 -1.40883579 -1.04842389]
 [ 0.27056487 -0.5729167   0.50081538 -0.01824279]
 [-0.88899886  1.7977731  -1.07

In [15]:
print(x_test) 

[[-1.1209116  -0.09877874 -1.35266958 -1.30596916]
 [-0.88899886  0.6124282  -1.18417095 -0.91965125]
 [-0.19326062  3.22018699 -1.29650337 -1.04842389]
 [ 0.27056487 -0.09877874  0.44464917  0.23930248]
 [ 0.1546085  -0.80998568  0.72548022  0.49684776]
 [ 0.85034673 -0.33584772  0.44464917  0.11052985]
 [ 0.73439036 -0.5729167   0.44464917  0.36807512]
 [-1.23686797  0.84949718 -1.24033716 -1.30596916]
 [-1.00495523  1.08656616 -1.40883579 -1.17719652]
 [ 0.38652124 -0.33584772  0.27615054  0.11052985]
 [ 0.9663031   0.13829024  0.33231675  0.23930248]
 [ 0.03865212  0.37535922  0.55698159  0.75439303]
 [-0.30921699 -0.09877874  0.38848296  0.36807512]
 [-0.19326062 -0.5729167   0.16381811  0.11052985]
 [ 0.61843399 -0.5729167   1.00631128  1.26948358]
 [ 0.38652124 -1.99533059  0.38848296  0.36807512]
 [-1.00495523  0.84949718 -1.24033716 -1.04842389]
 [-0.42517337  2.74604903 -1.35266958 -1.30596916]
 [-1.58473709 -1.75826161 -1.40883579 -1.17719652]
 [ 0.50247761  0.6124282   1.23

In [17]:
from sklearn.neighbors import KNeighborsClassifier  
classifier=KNeighborsClassifier(n_neighbors=3) 
classifier.fit(x_train,y_train) 
result=classifier.predict(x_test) 
print(result) 


['setosa' 'setosa' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'setosa' 'setosa' 'versicolor' 'versicolor' 'virginica'
 'versicolor' 'versicolor' 'virginica' 'versicolor' 'setosa' 'setosa'
 'versicolor' 'virginica' 'virginica' 'setosa' 'setosa' 'versicolor'
 'versicolor' 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica']


In [18]:
from sklearn.metrics import confusion_matrix,classification_report 
print(classification_report(y_test,result)) 
print(confusion_matrix(y_test,result))

              precision    recall  f1-score   support

      setosa       1.00      0.91      0.95        11
  versicolor       0.86      0.86      0.86        14
   virginica       0.67      0.80      0.73         5

    accuracy                           0.87        30
   macro avg       0.84      0.86      0.85        30
weighted avg       0.88      0.87      0.87        30

[[10  1  0]
 [ 0 12  2]
 [ 0  1  4]]


In [20]:
# Implementing the Support Vector Machine classifier
from sklearn.svm import SVC
classifier = SVC(kernel='linear')  
classifier.fit(x_train, y_train)

# Make predictions
result = classifier.predict(x_test)
print(result)

# Evaluate the model using classification report and confusion matrix
print(classification_report(y_test, result))
print(confusion_matrix(y_test, result))

['setosa' 'setosa' 'setosa' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'setosa' 'setosa' 'versicolor' 'versicolor' 'virginica'
 'versicolor' 'versicolor' 'virginica' 'versicolor' 'setosa' 'setosa'
 'setosa' 'virginica' 'virginica' 'setosa' 'setosa' 'versicolor'
 'versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'virginica']
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      0.86      0.92        14
   virginica       0.71      1.00      0.83         5

    accuracy                           0.93        30
   macro avg       0.90      0.95      0.92        30
weighted avg       0.95      0.93      0.94        30

[[11  0  0]
 [ 0 12  2]
 [ 0  0  5]]
