# torch.manual_seed()

torch.manual_seed() is a function in PyTorch that sets the seed for generating random numbers. This function helps control randomness in operations such as random initialization of model parameters, data shuffling, and other stochastic processes. Setting a manual seed ensures that results are reproducible, which is important when you want to compare experiments or debug code.

In [7]:
import torch
import random

random.seed(42)

print(random.random()) 


0.6394267984578837


# max() in PyTorch

In PyTorch, the max() function is used to find the maximum value or values in a tensor, and it can be applied in various contexts, depending on whether you want the maximum over the entire tensor or along specific dimensions.

In [8]:
import torch

tensor = torch.tensor([1.0, 3.0, 2.0, 5.0])

max_value = torch.max(tensor)
print(max_value) 


tensor(5.)


# min() in PyTorch

torch.min() is a function that returns the minimum value of a tensor or the minimum values along a specified dimension. It can either return a single scalar value for the entire tensor or return the minimum values along a specific axis.

In [9]:
import torch

x = torch.tensor([2.0, 3.5, -1.0, 7.0])

min_value = torch.min(x)
print(min_value) 


tensor(-1.)


# argmax()

In PyTorch, argmax() is a function used to return the index of the maximum value along a specified dimension (axis) of a tensor. It is often used in classification tasks to find the predicted class label from the output of a model, where the output is typically a vector of probabilities or scores for each class.

In [10]:
import torch

tensor = torch.tensor([[1, 3, 2], [4, 6, 5]])

max_indices = torch.argmax(tensor, dim=1)

print(max_indices) 


tensor([1, 1])


# argmin()

In PyTorch, torch.argmin() is a function that returns the indices of the minimum values along a specified dimension in a tensor.It is useful when you want to know the position of the smallest element(s) in a tensor. The result is a tensor of indices representing where the minimum values are located.

In [13]:
import torch

tensor = torch.tensor([[10, 2, 30], [15, 25, 5]])

index_min = torch.argmin(tensor, dim=1)

print(index_min)  # Output: tensor([1, 2])


tensor([1, 2])


# Difference between max() & argmax()

In PyTorch, both torch.max() and torch.argmax() deal with finding maximum values in a tensor, but they return different types of information:

### torch.max()
Purpose: Returns the maximum value itself, and optionally its index. 

Return: The maximum value (or the maximum values along a specific dimension). 

Usage: Used when you need the maximum value, not its location. 

### torch.argmax()
Purpose: Returns the index of the maximum value.

Return: The position (index) of the maximum value along the specified dimension.

Usage: Used when you need the position of the maximum value, not the value itself.

# Difference between min() & argmin()

In PyTorch, both torch.min() and torch.argmin() deal with finding minimum values in a tensor, but they return different types of information:

### torch.min()
Purpose: Returns the minimum value itself, and optionally its index. 

Return: The minimum value (or the minimum values along a specific dimension). 

Usage: Used when you need the minimum value, not its location. 

### torch.argmin()
Purpose: Returns the index of the minimum value.

Return: The position (index) of the minimum value along the specified dimension.

Usage: Used when you need the position of the minimum value, not the value itself.

# torch.stack()

torch.stack() is a function in PyTorch that concatenates a sequence of tensors along a new dimension. It takes a list or tuple of tensors, and it stacks them along a specified dimension to form a single tensor. All the input tensors must have the same shape.

In [14]:
import torch

tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

stacked_tensor = torch.stack([tensor1, tensor2], dim=0)
print(stacked_tensor)


tensor([[1, 2, 3],
        [4, 5, 6]])


# torch.view()

torch.view() in PyTorch is a method used to reshape a tensor without changing its data. It allows you to change the dimensions (shape) of a tensor as long as the total number of elements remains the same.

In [15]:
import torch

tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

reshaped_tensor = tensor.view(3, 2)
print(reshaped_tensor)


tensor([[1, 2],
        [3, 4],
        [5, 6]])


# torch.squeeze()

torch.squeeze() is a PyTorch function used to remove dimensions of size 1 from a tensor, making the tensor more compact. This is helpful when you want to eliminate unnecessary dimensions without changing the data.

In [16]:
import torch

x = torch.randn(1, 3, 1)
print(x.shape)  

y = torch.squeeze(x)
print(y.shape) 


torch.Size([1, 3, 1])
torch.Size([3])
