In [1]:
# Import PyTorch
import torch

list_a = [1, 2, 3, 4]

# Create a tensor from list_a
tensor_a = torch.tensor(list_a)

# Print the tensor
print(tensor_a)


tensor([1, 2, 3, 4])


In [2]:
import numpy as np
import torch

# Create two arrays using NumPy
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a
tensor_c = tensor_a - tensor_b

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b

# Add tensor_c to tensor_d
tensor_e = tensor_c + tensor_d

print(tensor_e)


tensor([ 1,  7, 15])


In [7]:
import torch
import torch.nn as nn

# Create the input tensor
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

model = nn.Sequential(
    nn.Linear(8, 5),  # First layer
    nn.Linear(5, 1),  # Second layer
    nn.Sigmoid()      # Activation function (Sigmoid)
)

output = model(input_tensor)

print(output)


tensor([[0.1552]], grad_fn=<SigmoidBackward0>)


In [9]:
import torch
import torch.nn as nn

# Define the neural network with three hidden layers
model = nn.Sequential(
    nn.Linear(12, 20),  
    nn.Linear(20, 14),  
    nn.Linear(14, 3),   
    nn.Linear(3, 2)     
)

# Example input tensor
input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1, 5, 3, 6, 9]])

# Forward pass through the model
output = model(input_tensor)
print(output)


tensor([[1.1896, 0.2423]], grad_fn=<AddmmBackward0>)


**Excercise**
Neural networks are a core component of deep learning models. They can power so much in your daily life, from language translation apps to the cameras on your smartphone. Which of the following statements about neural networks is true?

Answer the question(ad)

**Select all correct answers**


1). A neural network with a single linear layer followed by a sigmoid activation is similar to a logistic regression model.


2). A neural network can only contain two linear layers.


3). The softmax function takes a tensor of dimension N as input and outputs a float between zero and one.


4). The input dimension of a linear layer must be equal to the output dimension of the previous layer.

## Correct Answers:
1) True
4) True

# Sigmoid()

In [10]:
import torch
import torch.nn as nn

input_tensor = torch.tensor([[0.8]])

sigmoid = nn.Sigmoid()  
probability = sigmoid(input_tensor) 
print("Sigmoid Output:", probability)


Sigmoid Output: tensor([[0.6900]])


# Softmax()

In [11]:
softmax = nn.Softmax(dim=1) 
probability_softmax = softmax(input_tensor)  
print("Softmax Output:", probability_softmax)

Softmax Output: tensor([[1.]])


In [12]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

model = nn.Sequential(
    nn.Linear(8, 1),  
    nn.Sigmoid()      
)

output = model(input_tensor)
print("Output Probability:", output)


Output Probability: tensor([[0.0952]], grad_fn=<SigmoidBackward0>)


In [13]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

model = nn.Sequential(
    nn.Linear(11, 20),  
    nn.Linear(20, 15),  
    nn.Linear(15, 10),  
    nn.Linear(10, 1)    
)

output = model(input_tensor)
print("Regression Output:", output)


Regression Output: tensor([[-1.1923]], grad_fn=<AddmmBackward0>)


In [14]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

model = nn.Sequential(
    nn.Linear(11, 20),  
    nn.Linear(20, 15),  
    nn.Linear(15, 10), 
    nn.Linear(10, 4),   
    nn.Softmax(dim=1)  
)

output = model(input_tensor)
print("Multi-class Classification Output:", output)


Multi-class Classification Output: tensor([[0.2135, 0.2657, 0.2482, 0.2725]], grad_fn=<SoftmaxBackward0>)
